# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d16fc8a006510b9320f0c6b85befa9c4049bac4a327dcff47d0c5f9f911ab165968bbc5663cb43a08c6e2cf8be701a637d3787a0d34d9e8d6d6082151e5fe193

test:
  secret_key_base: c1473e6fda62c0de89683caa61411222d60fbfa9bd0086d0c6fc3b90e547dd314057aff75fabde95778b1996018143f686755f255cfeadda1d24657894afc8cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
